#frontend/DockerFile
FROM node:20-alpine AS builder

WORKDIR /app

# copiar archivos de dependencias
COPY package*.json ./
COPY vite.config.js ./

# Instalar dependencias
RUN npm ci --silent

# Copiar código fuente
COPY ..

# Construir aplicación
RUN npm run build

# Etapa de producción
FROM nginx:alpine

# Copiar configuración de nginx
COPY --from=builder /app/dist /app/dist /usr/share/nginx/html

# Exponer puerto
EXPOSE 80

# Iniciar nginx
CMD ["nginx", "-g", "daemon off;"]
