# Generated by Django 4.2 on 2025-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
