# Generated by Django 5.1.6 on 2025-03-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_client_is_client_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
