name: laser-store
services:
  db_products:
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_DEBUG: "True"
      JWT_SECRET_KEY: your_jwt_secret_here
      MONGO_URI: mongodb://mongo:27017/logs
      POSTGRES_DB: product_db
      POSTGRES_HOST: db_products
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      SECRET_KEY: django-insecure-01gtwm+&_5ci#*c-984mz*&(20&sl)7gqv-tio*q4sr
    image: postgres:14
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "54322"
        protocol: tcp
    volumes:
      - type: volume
        source: pgdata_products
        target: /var/lib/postgresql/data
        volume: {}
  mongo:
    image: mongo:6
    networks:
      default: null
    ports:
      - mode: ingress
        target: 27017
        published: "27017"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
        volume: {}
  product_service:
    build:
      context: D:\paginawebgrabadolaser\laser-store
      dockerfile: backend/product_service/Dockerfile
    depends_on:
      db_products:
        condition: service_started
        required: true
      mongo:
        condition: service_started
        required: true
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_DEBUG: "True"
      JWT_SECRET_KEY: your_jwt_secret_here
      MONGO_URI: mongodb://mongo:27017/logs
      POSTGRES_DB: product_db
      POSTGRES_HOST: db_products
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      SECRET_KEY: django-insecure-01gtwm+&_5ci#*c-984mz*&(20&sl)7gqv-tio*q4sr
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8002"
        protocol: tcp
    volumes:
      - type: bind
        source: D:\paginawebgrabadolaser\laser-store\backend\product_service
        target: /app
        bind:
          create_host_path: true
networks:
  default:
    name: laser-store_default
volumes:
  mongo_data:
    name: laser-store_mongo_data
  pgdata_products:
    name: laser-store_pgdata_products
