# Generated by Django 4.2 on 2025-02-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_user_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cliente',
            new_name='is_client',
        ),
    ]
