# Generated by Django 4.2 on 2025-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_cliente_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
